apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.nameOverride}}-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: {{.Values.secret.username}}
  password: {{.Values.secret.password}}
  